<?php
/**
 * Solwin Infotech
 * Solwin Contact Form Widget Extension
 *
 * @category   Solwin
 * @package    Solwin_Contactwidget
 * @copyright  Copyright © 2006-2016 Solwin (https://www.solwininfotech.com)
 * @license    https://www.solwininfotech.com/magento-extension-license/
 */
$widgetEnable = $block->getConfigValue('contactwidget_section/general/enable');
$captchaSitekey = $block->getConfigValue('contactwidget_section/recaptcha/recaptcha_sitekey');
$captchaTheme = $block->getConfigValue('contactwidget_section/recaptcha/recaptcha_theme');

//Form field Labeling
$namelabel = $block->getConfigValue('contactwidget_section/fieldlabeling/name');
$emaillabel = $block->getConfigValue('contactwidget_section/fieldlabeling/email');
$phonelabel = $block->getConfigValue('contactwidget_section/fieldlabeling/phonenumber');
$subjectlabel = $block->getConfigValue('contactwidget_section/fieldlabeling/subject');
$hearinglabel = $block->getConfigValue('contactwidget_section/fieldlabeling/hearing');
$interestlabel = $block->getConfigValue('contactwidget_section/fieldlabeling/interest');
$educationlabel = $block->getConfigValue('contactwidget_section/fieldlabeling/education');
$commentslabel = $block->getConfigValue('contactwidget_section/fieldlabeling/comments');

//Form field placeholder
$nameplaceholderlabel = $block->getConfigValue('contactwidget_section/placeholderlabeling/name');
$emailplaceholderlabel = $block->getConfigValue('contactwidget_section/placeholderlabeling/email');
$phoneplaceholderlabel = $block->getConfigValue('contactwidget_section/placeholderlabeling/phonenumber');
$subjectplaceholderlabel = $block->getConfigValue('contactwidget_section/placeholderlabeling/subject');
$commentsplaceholdercomments = $block->getConfigValue('contactwidget_section/placeholderlabeling/comments');

$formActionUrl = $block->getFormActionUrl();
$helper = $this->helper('Solwin\Contactwidget\Helper\Data');
$currPageUrl = $helper->getCurrentUrls();

$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();
$moduleManager = $objectManager->get('\Magento\Framework\Module\Manager');
$moduleEnabled = $moduleManager->isEnabled('Solwin_Contactwidget');
$HearUs = $objectManager->get('Solwin\Contactwidget\Model\Config\Source\HearUs')->toOptionArray();
$Interest = $objectManager->get('Solwin\Contactwidget\Model\Config\Source\Interest')->toOptionArray();
$Education = $objectManager->get('Solwin\Contactwidget\Model\Config\Source\Education')->toOptionArray();

?>
<?php if ($widgetEnable && $moduleEnabled) {?>
<form class="form contact" action="<?= /* @noEscape */ $formActionUrl ?>" id="contact-form" method="post" data-hasrequired="<?= $block->escapeHtml(__('* Required Fields')) ?>" data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset">
        <legend class="legend"><span><?= $block->escapeHtml($block->getData('cc_title')) ?></span></legend><br />
        <div class="field note no-label"><?= $block->escapeHtml($block->getData('cc_content')) ?></div>
        <div class="field name required">
            <label class="label" for="name"><span><?= $block->escapeHtml($namelabel) ?></span></label>
            <div class="control">
                <input name="name" id="name" title="<?= $block->escapeHtml($namelabel) ?>" class="input-text" placeholder="<?= $nameplaceholderlabel ?>" type="text" data-validate="{required:true}"/>
            </div>
        </div>
        <div class="field email required">
            <label class="label" for="email"><span><?= $block->escapeHtml($emaillabel) ?></span></label>
            <div class="control">
                <input name="email" id="email" title="<?= $block->escapeHtml($emaillabel) ?>" class="input-text" placeholder="<?= $emailplaceholderlabel ?>" type="email" data-validate="{required:true, 'validate-email':true}"/>
            </div>
        </div>
        <?php
        if ($block->getData('cc_enable_phoneno')) {
            ?>
        <div class="field telephone">
            <label class="label" for="telephone"><span><?= $block->escapeHtml($phonelabel) ?></span></label>
            <div class="control">
                <input name="telephone" id="telephone" placeholder="<?= $phoneplaceholderlabel ?>" title="<?= $block->escapeHtml($phonelabel) ?>" value="" class="input-text" type="text" />
            </div>
        </div>
        <?php } ?>
        <div class="field name required">
            <label class="label" for="subject"><span><?= $block->escapeHtml($subjectlabel) ?></span></label>
            <div class="control">
                <input name="subject" id="subject" title="<?= $block->escapeHtml($subjectlabel) ?>" class="input-text" placeholder="<?= $subjectplaceholderlabel ?>" type="text" data-validate="{required:true}"/>
            </div>
        </div>
        <div class="field hearing required">
            <label class="label" for="hearing"><span><?= $block->escapeHtml($hearinglabel) ?></span></label>
            <div class="control">
                <select multiple name="hearing[]" id="hearing" title="<?= $block->escapeHtml(__('Education')) ?>" class="validate-select" data-validate="{required:true}">
                    <?php foreach ($HearUs as $_HearUs) { ?>
                        <option value="<?= $_HearUs['value'] ?>"><?= $_HearUs['label'] ?></option>
                    <?php } ?>
                </select>
               
            </div>
        </div>
        <div class="field interest required">
            <label class="label" for="interest"><span><?= $block->escapeHtml($interestlabel) ?></span></label>
            <div class="control">
                <?php foreach ($Interest as $_Interest) { ?>
                    <input type="radio" name="interest" id="<?= $_Interest['label'] ?>" title="<?= $_Interest['label'] ?>" class="input-radio" value="<?= $_Interest['value'] ?>" data-validate="{required:true}"><?= $_Interest['label'] ?><br/>
                <?php } ?>
            </div>
        </div>
        <div class="field education required">
            <label class="label" for="education"><span><?= $block->escapeHtml($educationlabel) ?></span></label>
            <div class="control">
                <select name="education" id="education" title="<?= $block->escapeHtml(__('Education')) ?>" class="validate-select" data-validate="{required:true}">
                    <option value=""><?php echo __("--- Please Select ---"); ?></option>
                    <?php foreach ($Education as $_Education) { ?>
                        <option value="<?= $_Education['value'] ?>"><?= $_Education['label'] ?></option>
                    <?php } ?>
                </select>
            </div>
        </div>
        <div class="field comment required">
            <label class="label" for="comment"><span><?= $block->escapeHtml($commentslabel) ?></span></label>
            <div class="control">
                <textarea name="comment" placeholder="<?= $commentsplaceholdercomments ?>" id="comment" title="<?= $block->escapeHtml($commentslabel) ?>" class="input-text" cols="5" rows="3" data-validate="{required:true}"></textarea>
            </div>
        </div>
         <?php
            if ($block->getData('cc_enable_recaptcha') && ($captchaSitekey != "")) {
                ?>
        <div class="field comment required">
            <label class="label" for="captcha"><span><?= $block->escapeHtml(__('ReCaptcha')) ?></span></label>
            <div class="control">
                <script src="https://www.google.com/recaptcha/api.js"></script>
                <div class="g-recaptcha" data-sitekey="<?= /* @noEscape */ $captchaSitekey?>" data-theme="<?= /* @noEscape */ $captchaTheme ?>"></div>
            </div>
        </div>
        <?php } ?>

    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <input type="hidden" name="currUrl" id="currUrl" value="<?= /* @noEscape */ $currPageUrl ?>" />
            <input type="hidden" name="enablerecaptcha" id="currUrl" value="<?= /* @noEscape */ $block->getData('cc_enable_recaptcha') ?>" />
            <button type="submit" title="<?= $block->escapeHtml(__('Submit')) ?>" class="action submit primary">
                <span><?= $block->escapeHtml(__('Submit')) ?></span>
            </button>
        </div>
    </div>
</form>
    <?php
}
?>
<?php
if ($block->getData('cc_enable_recaptcha') && ($captchaSitekey != "")) { ?>
<style>
#contact-form .fieldset .field {
    width: calc(100% - 13px);
}
</style>
<?php } ?>
<style>
#contact-form {
    width: 100%;
}
#contact-form .action.submit.primary {
    margin-bottom: 10px;
}
#contact-form .g-recaptcha {
  transform: scale(0.8);
  -webkit-transform: scale(0.8);
  transform-origin: 0 0;
  -webkit-transform-origin: 0 0;
}
#contact-form .fieldset {
    margin-bottom: 10px;
}
</style>
